- hosts:  localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: creating instance
      gcp_compute_instance:
        name: "{{instance_name}}"
        machine_type: "{{machine_type}}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{source_image}}"
        network_interfaces:
          - access_configs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
        zone: "{{zone}}"
        project: "{{project_id}}"
        auth_kind: serviceaccount
        service_account_file: "{{service_account_file}}"
        state: present