---
- name: Add Docker CE repository
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker CE
  shell: dnf install docker-ce --nobest -y

- name: Install pip
  shell: dnf install python3 -y

- name: Install Docker SDK
  pip:
    name: docker-py

    
