---
- name: Enable Docker service to start on boot
  ansible.builtin.systemd:
    name: docker
    enabled: yes

- name: Enable Containerd service to start on boot
  ansible.builtin.systemd:
    name: containerd
    enabled: yes  

- name: Ensure Docker Daemon is running 
  ansible.builtin.systemd:
    name: docker
    state: started